### ISSUE TITLE
Not working since Dec 2021 on embedded videos

### ISSUE THREAD

**Issue by zhiruiwang** [devlab21/simple-vimeo-downloader-extension#10]
I used this extension very frequently over a year now, but it stopped working since Dec 2021, that it will always show "Processing..." for embedded Vimeo videos on the website I need to download from. It worked on the same website before. I remember it stopped working since it started to ask for permission, and it still doesn't work after granting the permission. Wonder whether this issue is awared and will have a fix? Thanks for the hard work maintaining this awesome tool!

**Comment by ycherniavskyi** [comment]
Could you please provide the Chrome Console output?

**Comment by ycherniavskyi** [comment]
Are you using the extension installed from chrome web store or from this repository?

**Comment by zhiruiwang** [comment]
Hi Yurii, thanks for getting back!

I am using the latest version 1.4.3 on the Chrome Extension store, and I also tried 1.0.6 from this repo, both don't work.

Please find the below screenshot of the Chrome Console output. 
<img width="555" alt="Screen Shot 2022-01-09 at 11 57 17 AM" src="https://user-images.githubusercontent.com/17771320/148692539-0fc5331e-afd1-4697-9ad3-9b6f43d48f52.png">

I am not very familiar with WebDev so not sure if I am sending the right output. How I got it was, I first go to the website with the video, use command + option + J to open the console, and press the icon of this extension, and it pops up a new window of "processing...". 
<img width="286" alt="Screen Shot 2022-01-09 at 11 59 13 AM" src="https://user-images.githubusercontent.com/17771320/148692576-b63fb09c-97ac-425e-a12d-ed86fc84b8aa.png">

The download buttons are not showing on the upper right corner of the video, and no new message shows up in the console as well. However, after I close the "processing..." window, it starts to show a GET and POST in the console, but still no download buttons on the video.

Let me know if you want me to try other things to help debug! Thank you very much!

**Comment by zhiruiwang** [comment]
Hi! Wonder if my console output above was helpful or not? I tried the newest 1.4.4 but still not working. Let me know if I could provide anything else! Thanks!

**Comment by zhiruiwang** [comment]
Tried 1.4.5 and still not working...

**Comment by zhiruiwang** [comment]
Try to use the extension to download videos from another subdomain of the same website and it works for every video there...Looking at what happens in the Chrome console with a **successful injection process** there:
![Screenshot 2022-01-29 10 24 19](https://user-images.githubusercontent.com/17771320/151666747-66d1a79a-3329-4423-ac50-e013815c252b.png)
There was no error message when I open the webpage, and after I click on the extension icon, the injection message showed up and the download button shows up on the screen.



And the error message from the subdomain in which **all the video downloads don't work**:
![Screenshot 2022-01-29 10 37 50](https://user-images.githubusercontent.com/17771320/151667401-e6601114-a95e-4481-b37e-54413d79b996.png)

When I open the webpage, all of those error messages and warnings pop up immediately. After clicking the extension icon, no new message shows up in the console.

Hope these screenshots help. Let me know if you need me to test any other things.

**Comment by zhiruiwang** [comment]
The latest version is working. Thanks for making the update! We can close the issue
