### ISSUE TITLE
Unable to download private embedded videos

### ISSUE THREAD

**Issue by AnessZurba** [devlab21/simple-vimeo-downloader-extension#2]
Today I'm suddenly not able to download private vimeo videos
I get 'No Injection occur' and then the logo gets injected to the video but no download options show up, I would have liked to share the link so you can reproduce it on your end, but since It's a private video it won't show up on your side
I hope you have access to some private vimeo videos that you can check this one.
I appreciate the work you have done in this extension, and hope that this problem can be easily fixed (I'm willing to help, my js skills aren't good though).

Thanks in advance,

**Comment by AnessZurba** [comment]
After a bit of tinkering, it seems the problems arises because the config file for private videos has changed
it gives the following instead of the fat JSON
`{"message": "Because of its privacy settings, this video cannot be played here.", "title": "Sorry", "view": 7}`

We'd need a workaround for this

**Comment by ycherniavskyi** [comment]
Hm, seam Vimeo provides some changing in its player. I'll try to check it tomorrow.
@AnessZurba thank you for your open issue.

**Comment by ycherniavskyi** [comment]
@AnessZurba just check on private videos which I have and everything work as expected. Maybe you could give me temporary access (by email necessary access data) to your private video to analyze and fix your issue.

**Comment by AnessZurba** [comment]
@ycherniavskyi 
Just to make sure, the error occurs when you try the extension on a video that is set to be hidden from vimeo, but allowed as embedded on a fixed set of domains (a whitelist).

Is this what you have checked?
I think my initial post wasn't clear enough on that, sorry - I'll fix the title too

**Comment by ycherniavskyi** [comment]
@AnessZurba it seems that to get such options (a whitelist and etc.) I need to have a paid account, which I haven't ☹️.
Could you give me temporary access to such video or add my domain to it?

**Comment by AnessZurba** [comment]
I don't have a paid account either, my friend registered for a 30 days trial to reproduce the behaviour,
I'll ask him to add you to the whitelist of such a video
Do you have a website that you can embed the video into?

**Comment by ycherniavskyi** [comment]
@AnessZurba yes I have my blog (which unfortunately did not get the necessary amount of love for a long time 😊) - devlab21.com. So you add my blog domain to whitelist and give me the embedded code snippet to a video for the test, and will fix the issue asap.

**Comment by AnessZurba** [comment]
OK
I'll register for a trial membership and do it

**Comment by AnessZurba** [comment]
`<iframe src="https://player.vimeo.com/video/336840487" width="640" height="266" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>`
here you go

**Comment by ycherniavskyi** [comment]
@AnessZurba it is strange, but I can inject downloader for the embedded video which you provide without any problem.
![image](https://user-images.githubusercontent.com/552025/58097874-0ac43680-7be1-11e9-92d1-9e64c0da7924.png)

**Comment by AnessZurba** [comment]
Strange indeed, please check your email

**Comment by ycherniavskyi** [comment]
@AnessZurba do you have this problem with the new extension version? Could I close the issue?

**Comment by AnessZurba** [comment]
Hi @ycherniavskyi 
Sorry, I don't have anything to test it with 
the website changed domain and is no longer using vimeo.

**Comment by ycherniavskyi** [comment]
@AnessZurba I see, then I close the issue. Feel free to open new one if you will get any problem with the extension.

**Comment by jmeugenio** [comment]
Here's an example of videos that are private, but whitelisted and viewable on some urls but that I cannot use the extension for:

https://vimeo.com/channels/618776/page:3

I am trying to grab the top video, LE BONHEUR....

**Comment by sophiemulders** [comment]
i have same problem.... it is a vimeo video but it is hosted on cdn from vimeo i think.
<img width="1440" alt="Schermafbeelding 2022-05-31 om 09 59 33" src="https://user-images.githubusercontent.com/34121370/171123107-b924c040-b596-4c1d-9de8-b5ce0016fabb.png">

**Comment by sophiemulders** [comment]
<img width="1440" alt="Schermafbeelding 2022-05-31 om 10 01 38" src="https://user-images.githubusercontent.com/34121370/171123373-55b44528-3bc8-4edd-ab1d-fb7b7576a86e.png">

**Comment by ycherniavskyi** [comment]
@sophiemulders, for now, this project is not related to the extension [Simple Downloader for Vimeo™](https://chrome.google.com/webstore/detail/simple-downloader-for-vim/mffmjlddchdccijipncbjhoabgmphjfb?hl=en-GB) on Chrome Web Store.
That is why I could suggest you contact the current publisher via Chrome Web Store.
