### ISSUE TITLE
content_script.js: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by daedroza** [devlab21/simple-vimeo-downloader-extension#4]
Hi, the extension fails here - 
`content_script.js:192 Inject Simple Vimeo Downloader Button into vimeo player on embed site`
`content_script.js:198   vimeo player is absent on [http://xyz.in/lesson/xyz/]`
`content_script.js:101 Uncaught TypeError: Cannot read property 'forEach' of undefined
    at downloadOptionsFromVimeoJSONToSidedockElemenAdd (content_script.js:101)
    at content_script.js:230
    at content_script.js:241
downloadOptionsFromVimeoJSONToSidedockElemenAdd @ content_script.js:101`
`(anonymous) @ content_script.js:230
(anonymous) @ content_script.js:241`

The player is present as embedded on the web page. However, the inject doesn't detect it.
The video name also includes '*' symbol. Other videos are working fine with same symbol though, could you please take a look?

**Comment by ycherniavskyi** [comment]
@daedroza Do I understand correct - `http://xyz.in/lesson/xyz/` is not the actual URL with the problem player? It will be much simpler to fix the issue if I have access to the exact or similar URL. (If you don't want to posit it in issue comment, you could send it to me by mail).

**Comment by ycherniavskyi** [comment]
@daedroza I just fix the reason of `TypeError` and publish it with version `1.2.1` (it is in Review for now), but unfortunately, I am not sure that it fixes the actual problem of not detected video. In any case, waiting for your status after update to the new version.

**Comment by ycherniavskyi** [comment]
Brr sorry, but I don't submit an actual fix for this issue with version `1.2.1`, so it will be shipped with version `1.2.2`.

**Comment by daedroza** [comment]
With current version (not updated), I found the solution. The XML file describes "ACCESS DENIED".

After debugging on where things went wrong, I found the URL itself was also the root cause of the problem. So your extension extracts the list of download link URL available from the final variable of the page (420p, 540p, 720p, etc).

My download link URL ended like this - 1336391009.mp4?source=1
If ?source=1 is set, the ACCESS DENIED XML page pops up. I don't have much knowledge of Javascript, but on bash, I used sed to remove it (trying to automate downloading a lot of videos).

I can confirm 99% of videos don't have ?source=1 parameter. Those URL which have the links fails to download.

EDIT: Can you please share me your user email? I can provide you the link (or better way - if you're on telegram, put a hi to @daedroza, we can fix the issue together).

**Comment by ycherniavskyi** [comment]
Hm strange, because I take the URL from Vimeo's video configuration json.

In any case, thank you for the issue, at last, the `TypeError` fixed.

@daedroza, and of course, I will appreciate for your positive feedback on Reviews 😉.

**Comment by daedroza** [comment]
With 1.2.2, I am able to download the video and there is no ?source=1 parameter in the URL. Looks fixed to me :)
