### ISSUE TITLE
Code changes to auto execute injection.

### ISSUE THREAD

**Issue by mmjsmohit** [devlab21/simple-vimeo-downloader-extension#7]
Hi! I want to auto execute injection of the link buttons instead of clicking on extension everytime I visit a page with Vimeo player embedded in it. I have already edited the allowed URLs in manifest.json but still the extension only works when I click it.
How can I edit the code such that it auto injects the download button everytime I visit a specified website?

**Comment by ycherniavskyi** [comment]
@mmjsmohit the idea of the current extension is to inject on request. If you want to inject on page load then you just need to set the appropriate handler of page load and call the inject method.

**Comment by mmjsmohit** [comment]
Actually I am a newbie in context to Chrome Extensions. Can you guide me how to do it?

**Comment by ycherniavskyi** [comment]
Sorry, but I can't read the Extension docs and StackOverflow for you. Starting query -  "browser extension page loaded handler" 🤷.

**Comment by mmjsmohit** [comment]
I understand. Thanks for your time. Cheers. ;-)
